references:
  default_job_config: &default_job_config
    working_directory: ~/tmp
    docker:
      # specify the version you desire here
      - image: circleci/node:9.10.0
        environment:
          NODE_ENV: test
version: 2
jobs:
  build:
    <<: *default_job_config
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  linter:
    <<: *default_job_config
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: npm run lint

  tests:
    <<: *default_job_config
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: npm run test


  release_stage:
    <<: *default_job_config
    steps:
      - attach_workspace:
          at: ~/tmp
      - run:
          name: Deploy Develop to Staging
          command: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_STAGING.git develop:master

  release_prod:
    <<: *default_job_config
    steps:
      - attach_workspace:
          at: ~/tmp
      - run:
          name: Deploy Master to Production
          command: git push -f  https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_PRODUCTION.git master

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build

      - linter:
          requires:
            - build

      - tests:
          requires:
            - linter

      - release_stage:
          requires:
            - build
            - linter
            - tests
          filters:
            branches:
              only:
                - develop

      - release_prod:
          requires:
            - build
            - linter
            - tests
          filters:
            branches:
              only:
                - master
